### ISSUE TITLE
Ability to run pagespeed report on static list of pages/urls

### ISSUE THREAD

**Issue by TraGicCode** [johansatge/psi-report#1]
I have a static list of urls ( which represent the major pages of my site ) that i would like to run page speed tests on.  It would be awesome if there was a way to feed in this list so i don't have to wait for the long process of the crawler crawling my whole website.

**Comment by johansatge** [comment]
Hi,

thank you for your feedback, this sounds great.

I'll try to have a look at how to implement it when I have some free time.

**Comment by johansatge** [comment]
Done in #3 thanks to @blaryjp.
